
-- GymSaaS Database Schema
-- Generated 2026-02-24
-- Multi-tenant SaaS architecture for gym management
-- Includes MercadoPago integration for multi-tenant payments
-- Each tenant (gym) has their own MercadoPago credentials to receive payments

BEGIN;

SET timezone = 'UTC';
SET session_replication_role = replica;

-- Drop existing objects
DROP VIEW IF EXISTS v_cupo_reservado CASCADE;
DROP VIEW IF EXISTS v_ocupacion_hoy CASCADE;
DROP VIEW IF EXISTS v_salas_mas_reservadas CASCADE;
DROP VIEW IF EXISTS v_suscripciones_ar CASCADE;
DROP VIEW IF EXISTS v_suscripciones_mensuales CASCADE;

DROP TABLE IF EXISTS password_reset_tokens CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS checkin CASCADE;
DROP TABLE IF EXISTS suscripcion_turno CASCADE;
DROP TABLE IF EXISTS suscripcion CASCADE;
DROP TABLE IF EXISTS rutina_plantilla_ejercicio CASCADE;
DROP TABLE IF EXISTS rutina_plantilla CASCADE;
DROP TABLE IF EXISTS ejercicio CASCADE;
DROP TABLE IF EXISTS turno_plantilla CASCADE;
DROP TABLE IF EXISTS plan_sala CASCADE;
DROP TABLE IF EXISTS sala CASCADE;
DROP TABLE IF EXISTS orden_pago CASCADE;
DROP TABLE IF EXISTS comprobante CASCADE;
DROP TABLE IF EXISTS estado_orden_pago CASCADE;
DROP TABLE IF EXISTS plan CASCADE;
DROP TABLE IF EXISTS socio CASCADE;
DROP TABLE IF EXISTS rol CASCADE;
DROP TABLE IF EXISTS personal CASCADE;
DROP TABLE IF EXISTS avatar CASCADE;
DROP TABLE IF EXISTS grupo_muscular CASCADE;
DROP TABLE IF EXISTS dia_semana CASCADE;
DROP TABLE IF EXISTS egreso CASCADE;
DROP TABLE IF EXISTS renovacion_suscripcion CASCADE;
DROP TABLE IF EXISTS configuracion_renovacion CASCADE;
DROP TABLE IF EXISTS caracteristicas_plan_saas CASCADE;
DROP TABLE IF EXISTS planes_saas CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS mercado_pago_credencial CASCADE;
DROP TABLE IF EXISTS webhook_retry CASCADE;
DROP TABLE IF EXISTS payment_audit CASCADE;
DROP TABLE IF EXISTS saas_mercadopago_subscriptions CASCADE;
DROP TABLE IF EXISTS metodo_pago CASCADE;
DROP TABLE IF EXISTS historial_pago_saas CASCADE;

-- ============================================
-- SaaS PLAN TABLES
-- ============================================

CREATE TABLE planes_saas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  descripcion varchar(255),
  precio_mensual numeric(10,2) NOT NULL,
  precio_anual numeric(10,2) NOT NULL,
  max_socios integer NOT NULL DEFAULT 0,  -- 0 = ilimitado
  max_personal integer NOT NULL DEFAULT 0,
  max_salas integer NOT NULL DEFAULT 0,
  max_turnos_por_dia integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT TRUE,
  orden integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone
);

CREATE TABLE caracteristicas_plan_saas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id integer NOT NULL,
  codigo varchar(50) NOT NULL,
  valor boolean NOT NULL DEFAULT TRUE,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  FOREIGN KEY (plan_id) REFERENCES planes_saas(id) ON DELETE CASCADE
);

-- ============================================
-- TENANT TABLE (Multi-tenancy)
-- ============================================

CREATE TABLE tenants (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  slug varchar(160),
  logo text,
  email varchar(320),
  telefono varchar(64),
  direccion varchar(255),
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1)),

  -- Plan SaaS (FK a planes_saas)
  plan_saas_id integer NOT NULL DEFAULT 1,
  plan_vence_en timestamp without time zone,
  plan_anual smallint NOT NULL DEFAULT 0 CHECK (plan_anual IN (0,1)),

  -- NOTA: El Tenant ID 1 es siempre SuperTenant (hardcoded en PlanSaaSService)
  -- No requiere campo en base de datos.

  -- Límites personalizados (override del plan)
  max_socios_override integer,
  max_personal_override integer,

  -- Branding personalizado (planes Premium y Enterprise)
  primary_color text,              -- Color primario en HEX (ej: '#FF5722')
  logo_url text,                   -- URL del logo personalizado (sobrescribe el campo logo)

  -- Fondos personalizados (planes Premium y Enterprise)
  background_image_url text,       -- URL de imagen de fondo para las vistas
  login_background_image_url text, -- URL de imagen de fondo específica para el login
  login_background_type text,      -- Tipo de fondo para login: 'image' o 'solid'
  login_background_color text,     -- Color de fondo sólido para login (cuando login_background_type = 'solid')

  -- Estadísticas y referidos
  fecha_registro timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  codigo_referido varchar(50),

  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,

  FOREIGN KEY (plan_saas_id) REFERENCES planes_saas(id)
);

-- ============================================
-- SHARED TABLES (tenants_id added)
-- ============================================

CREATE TABLE dia_semana (
  id smallint PRIMARY KEY,
  nombre varchar(20) NOT NULL
);

CREATE TABLE avatar (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url varchar(255) NOT NULL,
  nombre varchar(100),
  es_predeterminado smallint NOT NULL DEFAULT 0 CHECK (es_predeterminado IN (0,1)),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone
);

CREATE TABLE rol (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

CREATE TABLE grupo_muscular (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80) NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1
);

CREATE TABLE estado_orden_pago (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(50) NOT NULL,
  descripcion varchar(255),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_estado_orden_pago_nombre UNIQUE (nombre)
);

CREATE TABLE sala (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80) NOT NULL,
  cupo integer NOT NULL,
  activa smallint NOT NULL DEFAULT 1 CHECK (activa IN (0,1)),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_sala_nombre UNIQUE (nombre)
);

CREATE TABLE personal (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(160) NOT NULL,
  telefono varchar(10),
  direccion varchar(100) NOT NULL,
  especialidad varchar(100) NOT NULL,
  estado smallint NOT NULL DEFAULT 1 CHECK (estado IN (0,1)),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_personal_tenant_telefono UNIQUE (tenant_id, telefono)
);

-- Nota: El constraint uq_personal_telefono en DbContext es redundante con uq_personal_tenant_telefono

CREATE TABLE socio (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dni varchar(32) NOT NULL,
  nombre varchar(160) NOT NULL,
  email varchar(320) NOT NULL,
  telefono varchar(64),
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1)),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  fecha_nacimiento timestamp without time zone,
  CONSTRAINT uq_socio_dni UNIQUE (dni),
  CONSTRAINT uq_socio_email UNIQUE (email)
);

CREATE TABLE plan (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80) NOT NULL,
  dias_por_semana integer NOT NULL CHECK (dias_por_semana IN (2,3,5,7)),
  precio numeric(10,2) NOT NULL,
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1)),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_plan_tenant_nombre UNIQUE (tenant_id, nombre)
);

-- Tabla de relación muchos a muchos entre Plan y Sala
CREATE TABLE plan_sala (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id integer NOT NULL,
  sala_id integer NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_plan_sala UNIQUE (plan_id, sala_id),
  CONSTRAINT fk_plan_sala_plan FOREIGN KEY (plan_id) REFERENCES plan(id) ON DELETE CASCADE,
  CONSTRAINT fk_plan_sala_sala FOREIGN KEY (sala_id) REFERENCES sala(id) ON DELETE CASCADE
);

CREATE TABLE comprobante (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_url text NOT NULL,
  mime_type varchar(100),
  subido_en timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1
);

CREATE TABLE evolucion_fisica (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  peso numeric(5,2) NOT NULL,
  altura numeric(5,2),
  imc numeric(6,2),
  peso_ideal numeric(6,2),
  pecho numeric(5,2),
  cintura numeric(5,2),
  cadera numeric(5,2),
  brazo numeric(5,2),
  pierna numeric(5,2),
  gemelo numeric(5,2),
  observacion varchar(255),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1
);

CREATE TABLE orden_pago (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  plan_id integer NOT NULL,
  monto numeric(10,2) NOT NULL,
  vence_en timestamp without time zone NOT NULL,
  estado_id integer NOT NULL DEFAULT 1,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  notas text,
  comprobante_id integer,
  mercado_pago_preference_id varchar(100),
  mercado_pago_payment_id varchar(100),
  es_renovacion smallint NOT NULL DEFAULT 0,
  es_cambio_plan smallint NOT NULL DEFAULT 0, -- Indica si es un pago por diferencia de cambio de plan
  renovacion_id integer,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_orden_pago_socio_plan_creado UNIQUE (socio_id, plan_id, created_at)
);

-- ============================================
-- RENOVATION TABLES
-- ============================================

CREATE TABLE renovacion_suscripcion (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  plan_id integer NOT NULL,
  plan_id_anterior integer,
  orden_pago_id integer NOT NULL,
  suscripcion_nueva_id integer,
  fecha_renovacion timestamp without time zone NOT NULL,
  proximo_vencimiento timestamp without time zone NOT NULL,
  metodo_pago smallint NOT NULL,
  mercado_pago_preference_id varchar(100),
  mercado_pago_payment_id varchar(100),
  estado smallint NOT NULL DEFAULT 1,
  renovacion_automatica smallint NOT NULL DEFAULT 0,
  notas text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT chk_metodo_pago CHECK (metodo_pago IN (1, 2)),
  CONSTRAINT chk_estado_renovacion CHECK (estado IN (1, 2, 3, 4, 5))
);

CREATE TABLE configuracion_renovacion (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  renovacion_automatica_habilitada smallint NOT NULL DEFAULT 0,
  metodo_pago_preferido integer,
  mercado_pago_card_token varchar(255),
  ultimos_4_digitos varchar(4),
  ultima_renovacion timestamp without time zone,
  mercado_pago_preapproval_id text, -- ID de suscripción automática en MercadoPago
  mercado_pago_preapproval_status text, -- Estado de la suscripción automática
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_configuracion_renovacion_socio_id UNIQUE (socio_id)
);

CREATE TABLE ejercicio (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  tips text,
  video_url varchar(500),
  grupo_muscular_id integer,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1
);

CREATE TABLE rutina_plantilla (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  objetivo varchar(120),
  imagen_url varchar(255),
  grupo_muscular_id integer,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1
);

CREATE TABLE turno_plantilla (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sala_id integer NOT NULL,
  personal_id integer,
  dia_semana_id smallint NOT NULL,
  hora_inicio time NOT NULL,
  duracion_min integer NOT NULL CHECK (duracion_min BETWEEN 15 AND 240),
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1)),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1
);

CREATE TABLE rutina_plantilla_ejercicio (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rutina_id integer NOT NULL,
  ejercicio_id integer NOT NULL,
  orden integer NOT NULL DEFAULT 1,
  series integer,
  repeticiones integer,
  descanso_seg integer,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_rutpla_ej UNIQUE (rutina_id, ejercicio_id)
);

CREATE TABLE suscripcion (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  plan_id integer NOT NULL,
  inicio timestamp without time zone NOT NULL,
  fin timestamp without time zone NOT NULL,
  estado smallint NOT NULL DEFAULT 1 CHECK (estado IN (0,1)),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  orden_pago_id integer,
  tenant_id integer NOT NULL DEFAULT 1
);

CREATE TABLE suscripcion_turno (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suscripcion_id integer NOT NULL,
  turno_plantilla_id integer NOT NULL,
  rutina_id integer,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_sus_turno UNIQUE (suscripcion_id, turno_plantilla_id)
);

CREATE TABLE checkin (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  socio_id integer NOT NULL,
  turno_plantilla_id integer,
  profesor_id integer,
  fecha_hora timestamp without time zone NOT NULL,
  observaciones text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1
);

CREATE TABLE usuario (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(320) NOT NULL,
  alias varchar(100),
  rol_id integer,
  personal_id integer,
  socio_id integer,
  password_hash text NOT NULL,
  estado smallint NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  id_avatar integer,
  tenant_id integer NOT NULL DEFAULT 1,
  CONSTRAINT uq_usuario_email UNIQUE (email),
  CONSTRAINT uq_usuario_personal UNIQUE (personal_id),
  CONSTRAINT uq_usuario_avatar UNIQUE (id_avatar)
);

CREATE TABLE password_reset_tokens (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer NOT NULL,
  token varchar(255) NOT NULL,
  expira timestamp without time zone NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone
);

CREATE TABLE egreso (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  concepto varchar(255) NOT NULL,
  monto numeric(10,2) NOT NULL,
  fecha timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  categoria varchar(100),
  notas text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  tenant_id integer NOT NULL DEFAULT 1
);

-- ============================================
-- MERCADO PAGO INTEGRATION TABLES
-- ============================================

-- Credenciales OAuth de MercadoPago para cada tenant (gimnasio)
-- Cada empresa tiene sus propias credenciales para recibir pagos directamente
CREATE TABLE mercado_pago_credencial (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL,
  access_token text NOT NULL,
  refresh_token text,
  token_expira_en timestamp with time zone NOT NULL,
  mercado_pago_user_id bigint,
  public_key text,
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1)),
  fecha_autorizacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultimo_refresco timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone,
  CONSTRAINT uq_mercado_pago_credencial_tenant UNIQUE (tenant_id),
  CONSTRAINT fk_mercado_pago_credencial_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

-- Sistema de reintentos para webhooks de MercadoPago
-- Asegura que los pagos se procesen correctamente para cada tenant
CREATE TABLE webhook_retry (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id text NOT NULL,
  tipo text NOT NULL, -- payment/refunded/chargeback
  payload text NOT NULL, -- raw JSON para auditoría
  intentos integer NOT NULL DEFAULT 0,
  next_retry_at timestamp with time zone NOT NULL,
  completado boolean NOT NULL DEFAULT false,
  error_ultimo_intento text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  tenant_id integer
);

-- Auditoría de pagos de MercadoPago
-- Registra todos los eventos de pagos para trazabilidad
CREATE TABLE payment_audit (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer,
  type text NOT NULL, -- preference|payment|preapproval|webhook
  reference_id text NOT NULL, -- payment_id, preference_id, preapproval_id
  status text NOT NULL,
  amount numeric,
  currency text,
  email text,
  message text,
  payload text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- ============================================
-- SaaS MERCADO PAGO SUBSCRIPTIONS
-- ============================================

-- Suscripciones de MercadoPago para pagos SaaS de gimnasios
-- Una suscripción por tenant para gestionar cobros recurrentes del plan SaaS
CREATE TABLE saas_mercadopago_subscriptions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL UNIQUE,
  preapproval_id text NOT NULL UNIQUE, -- ID de la suscripción en MercadoPago
  status text NOT NULL, -- pending, authorized, paused, canceled
  plan_saas_id integer NOT NULL,
  es_anual boolean NOT NULL DEFAULT false,
  monto_mensual numeric NOT NULL,
  proximo_cobro timestamp without time zone NOT NULL,
  ultimo_cobro_exitoso timestamp without time zone,
  back_url text,
  motivo_pausa text,
  fecha_pausa timestamp without time zone,
  cobros_fallidos_consecutivos integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  CONSTRAINT fk_saas_mp_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_saas_mp_plan FOREIGN KEY (plan_saas_id) REFERENCES planes_saas(id)
);

-- ============================================
-- GESTIÓN DE PAGOS SAAS
-- ============================================

-- Métodos de pago de los tenants (gimnasios) para el SaaS
CREATE TABLE metodo_pago (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL,
  tipo varchar(50) NOT NULL, -- mercadopago, stripe, etc.
  token text, -- Token del método de pago (seguro)
  email varchar(320),
  estado integer NOT NULL DEFAULT 1, -- 1=Activo, 2=Suspendido, 3=Expirado, 4=Rechazado
  ultimo_4 char(4), -- Últimos 4 dígitos de la tarjeta
  marca varchar(50), -- Visa, Mastercard, etc.
  expiracion timestamp without time zone, -- Fecha de expiración de la tarjeta
  es_principal smallint NOT NULL DEFAULT 0, -- Método de pago principal
  mercado_pago_customer_id text, -- ID del cliente en MercadoPago
  mercado_pago_card_id text, -- ID de la tarjeta en MercadoPago
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  CONSTRAINT chk_metodo_pago_estado CHECK (estado IN (1, 2, 3, 4)),
  CONSTRAINT chk_metodo_pago_es_principal CHECK (es_principal IN (0, 1)),
  CONSTRAINT fk_metodo_pago_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);

-- Historial de pagos SaaS realizados por los tenants
CREATE TABLE historial_pago_saas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL,
  metodo_pago_id integer,
  plan_saas_id integer NOT NULL,
  monto numeric NOT NULL,
  estado integer NOT NULL, -- 1=Pendiente, 2=Exitoso, 3=Fallido, 4=Reembolsado, 5=Chargeback
  moneda varchar(3) DEFAULT 'ARS',
  fecha_intento timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_procesamiento timestamp without time zone,
  respuesta_gateway text, -- JSON con la respuesta del gateway
  mensaje_error text,
  transaccion_id text, -- ID de la transacción en el gateway
  intentos_realizados integer NOT NULL DEFAULT 1,
  es_renovacion_automatica smallint NOT NULL DEFAULT 1,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone,
  CONSTRAINT fk_historial_pagos_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE,
  CONSTRAINT fk_historial_pagos_metodo_pago FOREIGN KEY (metodo_pago_id) REFERENCES metodo_pago(id) ON DELETE SET NULL,
  CONSTRAINT fk_historial_pagos_plan_saas FOREIGN KEY (plan_saas_id) REFERENCES planes_saas(id)
);

-- ============================================
-- FOREIGN KEYS
-- ============================================

ALTER TABLE caracteristicas_plan_saas
  ADD CONSTRAINT fk_caracteristica_plan FOREIGN KEY (plan_id) REFERENCES planes_saas(id) ON DELETE CASCADE;

ALTER TABLE tenants
  ADD CONSTRAINT fk_tenant_plan_saas FOREIGN KEY (plan_saas_id) REFERENCES planes_saas(id);

ALTER TABLE ejercicio
  ADD CONSTRAINT fk_ejercicio_grupo FOREIGN KEY (grupo_muscular_id) REFERENCES grupo_muscular(id);

ALTER TABLE rutina_plantilla
  ADD CONSTRAINT fk_rutina_grupo FOREIGN KEY (grupo_muscular_id) REFERENCES grupo_muscular(id);

ALTER TABLE orden_pago
  ADD CONSTRAINT fk_orden_plan FOREIGN KEY (plan_id) REFERENCES plan(id),
  ADD CONSTRAINT fk_orden_socio FOREIGN KEY (socio_id) REFERENCES socio(id),
  ADD CONSTRAINT fk_orden_pago_estado FOREIGN KEY (estado_id) REFERENCES estado_orden_pago(id) ON UPDATE CASCADE,
  ADD CONSTRAINT fk_orden_pago_comprobante FOREIGN KEY (comprobante_id) REFERENCES comprobante(id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_orden_pago_renovacion FOREIGN KEY (renovacion_id) REFERENCES renovacion_suscripcion(id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE rutina_plantilla_ejercicio
  ADD CONSTRAINT fk_rpe_rutina FOREIGN KEY (rutina_id) REFERENCES rutina_plantilla(id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_rpe_ejercicio FOREIGN KEY (ejercicio_id) REFERENCES ejercicio(id);

ALTER TABLE turno_plantilla
  ADD CONSTRAINT fk_turno_sala FOREIGN KEY (sala_id) REFERENCES sala(id),
  ADD CONSTRAINT fk_turno_profesor FOREIGN KEY (personal_id) REFERENCES personal(id),
  ADD CONSTRAINT fk_dia_semana FOREIGN KEY (dia_semana_id) REFERENCES dia_semana(id) ON UPDATE CASCADE;

ALTER TABLE evolucion_fisica
  ADD CONSTRAINT fk_evolucion_socio FOREIGN KEY (socio_id) REFERENCES socio(id);

ALTER TABLE suscripcion
  ADD CONSTRAINT fk_sus_plan FOREIGN KEY (plan_id) REFERENCES plan(id),
  ADD CONSTRAINT fk_sus_socio FOREIGN KEY (socio_id) REFERENCES socio(id),
  ADD CONSTRAINT fk_suscripcion_orden FOREIGN KEY (orden_pago_id) REFERENCES orden_pago(id);

ALTER TABLE suscripcion_turno
  ADD CONSTRAINT fk_sust_sus FOREIGN KEY (suscripcion_id) REFERENCES suscripcion(id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_sust_turno FOREIGN KEY (turno_plantilla_id) REFERENCES turno_plantilla(id),
  ADD CONSTRAINT fk_rutina_suscripcionturno FOREIGN KEY (rutina_id) REFERENCES rutina_plantilla(id);

ALTER TABLE renovacion_suscripcion
  ADD CONSTRAINT fk_renovacion_socio FOREIGN KEY (socio_id) REFERENCES socio(id) ON DELETE CASCADE,
  ADD CONSTRAINT fk_renovacion_plan FOREIGN KEY (plan_id) REFERENCES plan(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT fk_renovacion_plan_anterior FOREIGN KEY (plan_id_anterior) REFERENCES plan(id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_renovacion_orden_pago FOREIGN KEY (orden_pago_id) REFERENCES orden_pago(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT fk_renovacion_suscripcion_nueva FOREIGN KEY (suscripcion_nueva_id) REFERENCES suscripcion(id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE configuracion_renovacion
  ADD CONSTRAINT fk_configuracion_socio FOREIGN KEY (socio_id) REFERENCES socio(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE checkin
  ADD CONSTRAINT fk_check_socio FOREIGN KEY (socio_id) REFERENCES socio(id),
  ADD CONSTRAINT fk_check_turno FOREIGN KEY (turno_plantilla_id) REFERENCES turno_plantilla(id),
  ADD CONSTRAINT fk_checkin_profesor FOREIGN KEY (profesor_id) REFERENCES personal(id) ON DELETE SET NULL;

ALTER TABLE usuario
  ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES rol(id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_usuario_profesor FOREIGN KEY (personal_id) REFERENCES personal(id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_usuario_socio FOREIGN KEY (socio_id) REFERENCES socio(id) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT fk_usuario_avatar FOREIGN KEY (id_avatar) REFERENCES avatar(id);

ALTER TABLE password_reset_tokens
  ADD CONSTRAINT fk_password_reset_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE ON UPDATE CASCADE;

-- Egresos (no tiene foreign keys, es una tabla independiente)

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX idx_check_socio_fecha ON checkin (socio_id, fecha_hora);
CREATE INDEX idx_check_turno ON checkin (turno_plantilla_id);
CREATE INDEX idx_checkin_profesor ON checkin (profesor_id);
CREATE INDEX idx_orden_socio ON orden_pago (socio_id);
CREATE INDEX idx_orden_plan ON orden_pago (plan_id);
CREATE INDEX idx_orden_estado ON orden_pago (estado_id);
CREATE INDEX idx_orden_comprobante ON orden_pago (comprobante_id);
CREATE INDEX idx_rpe_ejercicio ON rutina_plantilla_ejercicio (ejercicio_id);
CREATE INDEX idx_sus_socio ON suscripcion (socio_id);
CREATE INDEX idx_sus_plan ON suscripcion (plan_id);
CREATE INDEX idx_sus_orden ON suscripcion (orden_pago_id);
CREATE INDEX idx_sust_turno ON suscripcion_turno (turno_plantilla_id);
CREATE INDEX idx_sust_rutina ON suscripcion_turno (rutina_id);
CREATE INDEX idx_evolucion_socio ON evolucion_fisica (socio_id);
CREATE INDEX idx_estado_orden_pago_tenant ON estado_orden_pago (tenant_id);
CREATE INDEX idx_egreso_tenant ON egreso (tenant_id);
CREATE INDEX idx_egreso_fecha ON egreso (fecha);

-- Renovation indexes
CREATE INDEX idx_renovacion_socio_fecha ON renovacion_suscripcion (socio_id, fecha_renovacion DESC);
CREATE UNIQUE INDEX uq_renovacion_preference_id ON renovacion_suscripcion (mercado_pago_preference_id) WHERE mercado_pago_preference_id IS NOT NULL;
CREATE UNIQUE INDEX uq_renovacion_payment_id ON renovacion_suscripcion (mercado_pago_payment_id) WHERE mercado_pago_payment_id IS NOT NULL;
CREATE INDEX idx_renovacion_estado ON renovacion_suscripcion (estado);
CREATE INDEX idx_renovacion_renovacion_auto ON renovacion_suscripcion (renovacion_automatica) WHERE renovacion_automatica = 1;
CREATE INDEX idx_configuracion_socio ON configuracion_renovacion (socio_id);
CREATE INDEX idx_configuracion_auto_habilitada ON configuracion_renovacion (renovacion_automatica_habilitada) WHERE renovacion_automatica_habilitada = 1;
CREATE INDEX idx_orden_pago_renovacion ON orden_pago (renovacion_id);
CREATE INDEX idx_orden_pago_preference_id ON orden_pago (mercado_pago_preference_id) WHERE mercado_pago_preference_id IS NOT NULL;
CREATE INDEX idx_orden_pago_payment_id ON orden_pago (mercado_pago_payment_id) WHERE mercado_pago_payment_id IS NOT NULL;
CREATE INDEX idx_orden_pago_es_renovacion ON orden_pago (es_renovacion) WHERE es_renovacion = 1;

-- MercadoPago indexes
CREATE INDEX idx_mercado_pago_credencial_tenant ON mercado_pago_credencial (tenant_id);
CREATE INDEX idx_mercado_pago_credencial_activo ON mercado_pago_credencial (activo) WHERE activo = 1;
CREATE INDEX idx_webhook_retry_payment_id ON webhook_retry (payment_id);
CREATE INDEX idx_webhook_retry_tenant ON webhook_retry (tenant_id);
CREATE INDEX idx_webhook_retry_completado ON webhook_retry (completado) WHERE completado = false;
CREATE INDEX idx_webhook_retry_next_retry ON webhook_retry (next_retry_at) WHERE completado = false;
CREATE INDEX idx_payment_audit_tenant ON payment_audit (tenant_id);
CREATE INDEX idx_payment_audit_reference ON payment_audit (reference_id);
CREATE INDEX idx_payment_audit_type ON payment_audit (type);
CREATE INDEX idx_payment_audit_created ON payment_audit (created_at DESC);

-- SaaS MercadoPago subscriptions indexes
CREATE INDEX idx_saas_mp_tenant ON saas_mercadopago_subscriptions (tenant_id);
CREATE INDEX idx_saas_mp_status ON saas_mercadopago_subscriptions (status);
CREATE INDEX idx_saas_mp_proximo_cobro ON saas_mercadopago_subscriptions (proximo_cobro);
CREATE INDEX idx_saas_mp_plan ON saas_mercadopago_subscriptions (plan_saas_id);

-- SaaS Payment methods indexes
CREATE INDEX idx_metodo_pago_tenant ON metodo_pago (tenant_id);
CREATE INDEX idx_metodo_pago_es_principal ON metodo_pago (es_principal);
CREATE INDEX idx_metodo_pago_estado ON metodo_pago (estado);

-- SaaS Payment history indexes
CREATE INDEX idx_historial_pagos_tenant ON historial_pago_saas (tenant_id);
CREATE INDEX idx_historial_pagos_metodo_pago ON historial_pago_saas (metodo_pago_id);
CREATE INDEX idx_historial_pagos_plan_saas ON historial_pago_saas (plan_saas_id);
CREATE INDEX idx_historial_pagos_estado ON historial_pago_saas (estado);
CREATE INDEX idx_historial_pagos_fecha ON historial_pago_saas (fecha_intento DESC);

-- PlanSala - Índices para optimizar consultas de planes-salas
CREATE INDEX idx_plan_sala_plan ON plan_sala (plan_id);
CREATE INDEX idx_plan_sala_sala ON plan_sala (sala_id);
CREATE INDEX idx_plan_sala_tenant ON plan_sala (tenant_id);

-- ============================================
-- SEED DATA
-- ============================================

-- Days of week
INSERT INTO dia_semana (id, nombre) VALUES
(1, 'Lunes'),
(2, 'Martes'),
(3, 'Miércoles'),
(4, 'Jueves'),
(5, 'Viernes'),
(6, 'Sábado'),
(7, 'Domingo');

-- SaaS Plans
INSERT INTO planes_saas (id, nombre, descripcion, precio_mensual, precio_anual, max_socios, max_personal, max_salas, max_turnos_por_dia, activo, orden) VALUES
(1, 'Basic', 'Para gimnasios pequeños', 14995, 149950, 50, 5, 3, 20, 1, 1),
(2, 'Standard', 'Para gimnasios en crecimiento', 29990, 299900, 200, 15, 10, 50, 1, 2),
(3, 'Premium', 'Para gimnasios establecidos', 79990, 799900, 500, 30, 20, 100, 1, 3),
(4, 'Enterprise', 'Sin límites', 199990, 1999900, 0, 0, 0, 0, 1, 4);

-- SaaS Plan Characteristics
INSERT INTO caracteristicas_plan_saas (plan_id, codigo, valor) VALUES
-- Basic plan features
(1, 'tiene_rutinas', 1),
(1, 'tiene_checkin', 1),
-- Features NOT available in Basic
(1, 'tiene_evolucion_fisica', 0),
(1, 'tiene_reportes_avanzados', 0),
(1, 'tiene_app_personalizada', 0),
(1, 'tiene_soporte_prioritario', 0),
(1, 'tiene_api_acceso', 0),
(1, 'tiene_integraciones', 0),
-- Standard plan features
(2, 'tiene_rutinas', 1),
(2, 'tiene_evolucion_fisica', 1),
(2, 'tiene_checkin', 1),
(2, 'tiene_reportes_avanzados', 1),
-- Features NOT available in Standard
(2, 'tiene_app_personalizada', 0),
(2, 'tiene_soporte_prioritario', 0),
(2, 'tiene_api_acceso', 0),
(2, 'tiene_integraciones', 0),
-- Premium plan features
(3, 'tiene_rutinas', 1),
(3, 'tiene_evolucion_fisica', 1),
(3, 'tiene_checkin', 1),
(3, 'tiene_reportes_avanzados', 1),
(3, 'tiene_app_personalizada', 1),
(3, 'tiene_soporte_prioritario', 1),
-- Features NOT available in Premium
(3, 'tiene_api_acceso', 0),
(3, 'tiene_integraciones', 0),
-- Enterprise plan (all features enabled)
(4, 'tiene_rutinas', 1),
(4, 'tiene_evolucion_fisica', 1),
(4, 'tiene_checkin', 1),
(4, 'tiene_reportes_avanzados', 1),
(4, 'tiene_app_personalizada', 1),
(4, 'tiene_soporte_prioritario', 1),
(4, 'tiene_api_acceso', 1),
(4, 'tiene_integraciones', 1);

-- Default Tenant (ID 1 es SuperTenant por hardcoded en PlanSaaSService)
INSERT INTO tenants (id, nombre, slug, email, activo, plan_saas_id, primary_color, fecha_registro) VALUES
(1, 'Gym Demo', 'demo', 'admin@gymdemo.com', 1, 4, '#ff6b00', CURRENT_TIMESTAMP);

-- Roles
INSERT INTO rol (id, nombre) VALUES
(1, 'Administrador'),
(2, 'Profesor'),
(3, 'Recepcion'),
(4, 'Socio');

-- Estados de Orden de Pago
INSERT INTO estado_orden_pago (id, nombre, descripcion, tenant_id) VALUES
(1, 'Pendiente', 'Esperando aprobación del comprobante de pago', 1),
(2, 'En Revision', 'Comprobante de pago en revisión', 1),
(3, 'Aprobada', 'Pago aprobado y suscripción activada', 1),
(4, 'Rechazada', 'Pago rechazado por el administrador', 1),
(5, 'Cancelada', 'Orden de pago cancelada por el socio', 1);

-- Default Avatars
INSERT INTO avatar (id, url, nombre, es_predeterminado) VALUES
(1, '/images/avatars/default.png', 'Default', 1);

-- Default Admin User (tenant_id = 1)
INSERT INTO usuario (id, email, alias, password_hash, rol_id, estado, id_avatar, tenant_id) VALUES
(1, 'admin@gym.com', 'admin', '$2a$11$CaVdIg35j00ZDqM0jVCk6urul1expo6n7FKHGXPKxNP/q7T4pPbQW', 1, 1, 1, 1);

-- Re-enable constraints
SET session_replication_role = DEFAULT;

COMMIT;
